language: node_js

node_js: 
  - "10.15.3"

install:
  - npm install

cache: npm

script:
  - nyc --reporter=lcov npm run test

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: npm run coverage
